import { geoJSONFromRegions } from '../spatial/map/geojson.js';
const esc=v=>{const s=v==null?'':String(v);return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s;};
export function downloadBlob(filename,blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),800);}
export function downloadText(filename,text,type='text/plain;charset=utf-8'){downloadBlob(filename,new Blob([text],{type}));}
function mapFrame(frame){return[...frame.entries()].map(([regionId,r])=>({regionId,...r}));}
export function serializeRun(run){return{...run,history:run.history.map(mapFrame)};} export function deserializeRun(run){return{...run,history:(run.history||[]).map(rows=>new Map(rows.map(r=>[r.regionId,{...r}])))};}
export function projectPayload(state,includeRuns=true){return{schemaVersion:'4.4.0',project:{...state.project,schemaVersion:'4.4.0'},space:state.space,grid:state.grid,simulationConfig:state.simulationConfig,propagation:state.propagation,regions:[...state.regions.values()],analysisOptions:state.analysisOptions,dirty:state.dirty,runs:includeRuns?state.runs.map(serializeRun):[]};}
export function projectJSON(state,includeRuns=true){return JSON.stringify(projectPayload(state,includeRuns),null,2);} export function runJSON(run){return JSON.stringify(serializeRun(run),null,2);}
export function temporalCSV(run){const h=['run_id','spatial_mode','seed','time','region_id','region_name','population','susceptible','infected','recovered','vaccinated','path_susceptibility_multiplier','barrier_vaccination_pct','new_infections','new_recoveries','new_vaccinations','local_infections','imported_infections','active_origin','origin_id','active_focus','focus_id','received_jump','jump_id'];const rows=[h.join(',')],names=new Map((run.regions||[]).map(r=>[r.id,r.name]));run.history.forEach((frame,t)=>{for(const[id,r]of frame)rows.push([run.id,run.space?.mode||'grid',run.seed,t,id,names.get(id)||id,r.population,r.susceptible,r.infected,r.recovered,r.vaccinated,r.pathSusceptibilityMultiplier??1,r.barrierVaccinationPct??'',r.newInfections||0,r.newRecoveries||0,r.newVaccinations||0,r.localInfections||0,r.importedInfections||0,r.activeOrigin?1:0,r.activeOriginId||'',r.activeFocus?1:0,r.activeFocusId||'',r.receivedJump?1:0,r.receivedJumpId||''].map(esc).join(','));});return rows.join('\n');}
export function eventsCSV(run){const keys=['time','type','originId','focusId','jumpId','regionId','sourceRegionId','targetRegionId','infectedCount','infectedIntroduced','reason'];const rows=[keys.join(',')];for(const e of run.eventLog||[])rows.push(keys.map(k=>esc(e[k])).join(','));return rows.join('\n');}
export function edgesCSV(run){const keys=['id','sourceRegionId','targetRegionId','type','baseWeight','multiplier','effectiveWeight','normalizedWeight','enabled','blockedByVaccination'];const rows=[keys.join(',')];for(const e of run.edges||[])rows.push(keys.map(k=>esc(e[k])).join(','));return rows.join('\n');}
export function regionsCSV(run){const keys=['region_id','region_name','spatial_mode','population','initial_susceptible','initial_infected','initial_recovered','initial_vaccinated','initial_vaccinated_pct','path_susceptibility_multiplier','barrier_vaccination_pct','arrival_time','peak_time','peak_infected'];const rows=[keys.join(',')],summary=run.summary||{},regionMap=new Map((run.regions||[]).map(r=>[r.id,r]));for(const id of regionMap.keys()){const arrival=summary.arrivals?.[id],p=summary.regionPeaks?.[id]||{},base=run.history[0]?.get(id),meta=regionMap.get(id);rows.push([id,meta?.name||id,run.space?.mode||'grid',base?.population||'',base?.susceptible??'',base?.infected??'',base?.recovered??'',base?.vaccinated??'',base?.population?((100*base.vaccinated/base.population).toFixed(3)):'',base?.pathSusceptibilityMultiplier??1,base?.barrierVaccinationPct??'',arrival??'',p.time??'',p.infected??''].map(esc).join(','));}return rows.join('\n');}
export function regionsGeoJSON(run){const regions=new Map((run.regions||[]).map(r=>[r.id,r]));if(![...regions.values()].some(r=>r.geometry))return null;const props={};for(const[id,r]of regions){const p=run.summary?.regionPeaks?.[id]||{};props[id]={arrival_time:run.summary?.arrivals?.[id]??null,peak_time:p.time??null,peak_infected:p.infected??null,initial_vaccinated_pct:r.population?100*r.vaccinated/r.population:0,path_susceptibility_multiplier:r.pathSusceptibilityMultiplier??1,barrier_vaccination_pct:r.barrierVaccinationPct??null};}return JSON.stringify(geoJSONFromRegions(regions,props),null,2);}
