function pearson(a,b){const n=Math.min(a.length,b.length);if(n<2)return 0;const ma=a.slice(0,n).reduce((s,x)=>s+x,0)/n,mb=b.slice(0,n).reduce((s,x)=>s+x,0)/n;let num=0,da=0,db=0;for(let i=0;i<n;i++){const x=a[i]-ma,y=b[i]-mb;num+=x*y;da+=x*x;db+=y*y;}return da>0&&db>0?num/Math.sqrt(da*db):0;}
function directionFromArrivals(arrivals, regions){const pts=[];for(const [id,t] of arrivals){if(t==null)continue;const r=regions.get(id);if(r)pts.push([r.column,r.row,t]);}if(pts.length<3)return{direction:'indefinida',confidence:0};const mx=pts.reduce((s,p)=>s+p[0],0)/pts.length,my=pts.reduce((s,p)=>s+p[1],0)/pts.length,mt=pts.reduce((s,p)=>s+p[2],0)/pts.length;let sxx=0,syy=0,sxy=0,sxt=0,syt=0;for(const [x,y,t] of pts){const dx=x-mx,dy=y-my,dt=t-mt;sxx+=dx*dx;syy+=dy*dy;sxy+=dx*dy;sxt+=dx*dt;syt+=dy*dt;}const det=sxx*syy-sxy*sxy;let a,b;if(Math.abs(det)<1e-9){if(sxx>1e-9&&syy<=1e-9){a=sxt/sxx;b=0;}else if(syy>1e-9&&sxx<=1e-9){a=0;b=syt/syy;}else return{direction:'indefinida',confidence:0};}else{a=(sxt*syy-syt*sxy)/det;b=(syt*sxx-sxt*sxy)/det;}const mag=Math.hypot(a,b);if(mag<1e-9)return{direction:'indefinida',confidence:0};let ssTot=0,ssRes=0;for(const [x,y,t] of pts){const pred=mt+a*(x-mx)+b*(y-my);ssTot+=(t-mt)**2;ssRes+=(t-pred)**2;}const r2=ssTot>0?Math.max(0,Math.min(1,1-ssRes/ssTot)):0;const angle=Math.atan2(b,a)*180/Math.PI;const dirs=[['east',0],['southeast',45],['south',90],['southwest',135],['west',180],['northwest',-135],['north',-90],['northeast',-45]];let best=dirs[0],dist=999;for(const d of dirs){let delta=Math.abs(angle-d[1]);delta=Math.min(delta,360-delta);if(delta<dist){dist=delta;best=d;}}return{direction:best[0],angleDegrees:angle,confidence:r2};}
export function analyzeRun(run, regions, options={}){
  const threshold=Math.max(1,Number(options.arrivalThreshold)||1);const arrivals=new Map(),peaks=new Map();let globalPeak={time:0,infected:0};let totalPopulation=0;const first=run.history[0];for(const [id,r] of first){totalPopulation+=r.population;arrivals.set(id,null);peaks.set(id,{time:0,infected:r.infected});}
  const totals=[];let lastActive=0;run.history.forEach((frame,t)=>{let I=0,S=0,R=0,V=0;for(const [id,r] of frame){I+=r.infected;S+=r.susceptible;R+=r.recovered;V+=r.vaccinated;if(arrivals.get(id)==null&&r.infected>=threshold)arrivals.set(id,t);const p=peaks.get(id);if(r.infected>p.infected)peaks.set(id,{time:t,infected:r.infected});}if(I>0)lastActive=t;if(I>globalPeak.infected)globalPeak={time:t,infected:I};totals.push({time:t,susceptible:S,infected:I,recovered:R,vaccinated:V});});
  let peakRegion={regionId:null,time:0,infected:-1};for(const [id,p] of peaks)if(p.infected>peakRegion.infected)peakRegion={regionId:id,...p};
  const reached=[...arrivals.entries()].filter(([,t])=>t!=null).length;const jumps=run.eventLog.filter(e=>e.type==='jump_executed');const observedDirection=directionFromArrivals(arrivals,regions);
  const correlations=[];const referenceId=options.referenceRegionId;if(referenceId&&regions.has(referenceId)){const ref=run.history.map(f=>f.get(referenceId)?.infected||0);for(const id of regions.keys()){if(id===referenceId)continue;correlations.push({regionId:id,correlation:pearson(ref,run.history.map(f=>f.get(id)?.infected||0))});}correlations.sort((a,b)=>b.correlation-a.correlation);}
  return {threshold,totalPopulation,reachedRegions:reached,totalRegions:regions.size,attackReach:regions.size?reached/regions.size:0,duration:lastActive,globalPeak,peakRegion,executedJumps:jumps.length,observedDirection,arrivals:Object.fromEntries(arrivals),regionPeaks:Object.fromEntries(peaks),totals,topCorrelations:correlations.slice(0,8)};
}
